import { NextResponse } from 'next/server';
import { getPrisma } from '@/lib/db/prisma';

// Product data from mockProducts
const seedProducts = [
  // ==================== AIRBORNE (DRONES) ====================
  {
    sku: 'AU-XAG-PROP4',
    slug: 'p100-pro-basic-package',
    name: 'XAG P100 Pro Basic Package',
    tagline: 'Complete spray package with 50L tank, 4 batteries, 2 chargers',
    mainImage: '/images/products/drones/au-xag-prop4-1.png',
    price: 10920000,
    priceEUR: 2540000,
    compareAtPrice: 12896000,
    compareAtPriceEUR: 2999000,
    stock: 5,
    category: 'Airborne',
    type: 'PRODUCT',
  },
  {
    sku: '09-007-00136',
    slug: 'p100-pro',
    name: 'XAG P100 Pro',
    tagline: '50kg payload, 50L tank, SuperX 4 Pro flight control',
    mainImage: '/images/products/drones/09-007-00136-1.png',
    price: 6292000,
    priceEUR: 1463000,
    compareAtPrice: 7800000,
    compareAtPriceEUR: 1814000,
    stock: 3,
    category: 'Airborne',
    type: 'PRODUCT',
  },
  {
    sku: 'AU-XAG-PROP5',
    slug: 'p100-pro-spreader-package',
    name: 'XAG P100 Pro Spreader Package',
    tagline: 'Spray + Spread package with RevoSpray P3 & RevoCast P3',
    mainImage: '/images/products/drones/au-xag-prop5-1.png',
    price: 11700000,
    priceEUR: 2721000,
    compareAtPrice: 14081600,
    compareAtPriceEUR: 3275000,
    stock: 2,
    category: 'Airborne',
    type: 'PRODUCT',
  },
  {
    sku: 'AU-XAG-PROP6',
    slug: 'p100-pro-rtk-package',
    name: 'XAG P100 Pro Package + RTK',
    tagline: 'Full package with RTK for centimetre-level precision',
    mainImage: '/images/products/drones/au-xag-prop6-1.png',
    price: 12480000,
    priceEUR: 2902000,
    compareAtPrice: 15293200,
    compareAtPriceEUR: 3556000,
    stock: 1,
    category: 'Airborne',
    type: 'PRODUCT',
  },

  // ==================== LANDBORNE (UGV) ====================
  {
    sku: 'XAG-R200',
    slug: 'xag-r200',
    name: 'XAG R200',
    tagline: 'Six-wheel precision spraying platform for orchards and greenhouses',
    mainImage: '/images/products/ugv/r200.png',
    price: 9815400,
    priceEUR: 2282000,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 2,
    category: 'Landborne',
    type: 'PRODUCT',
  },

  // ==================== SMART BATTERY ====================
  {
    sku: '09-017-00064',
    slug: 'smart-battery-b13970s',
    name: 'XAG Smart Battery B13970S',
    tagline: 'High-capacity smart battery for P150 series',
    mainImage: '/images/products/smart-battery/09-017-00064-1.jpg',
    price: 743600,
    priceEUR: 172900,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 10,
    category: 'Smart Battery',
    type: 'ACCESSORY',
  },
  {
    sku: '09-017-00025',
    slug: 'smart-battery-b13960s',
    name: 'XAG Smart Battery B13960S',
    tagline: '20,000 mAh / 962 Wh - IP65 rated lithium polymer',
    mainImage: '/images/products/smart-battery/09-017-00025-1.png',
    price: 494000,
    priceEUR: 114900,
    compareAtPrice: 743600,
    compareAtPriceEUR: 172900,
    stock: 15,
    category: 'Smart Battery',
    type: 'ACCESSORY',
  },
  {
    sku: '01-027-01895',
    slug: 'battery-outlet-socket-b13960s',
    name: 'B13960S Battery Outlet Socket',
    tagline: 'Battery outlet socket component',
    mainImage: '/images/products/smart-battery/01-027-01895-1.png',
    price: 57200,
    priceEUR: 13300,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Smart Battery',
    type: 'ACCESSORY',
  },
  {
    sku: '05-002-00759',
    slug: 'smart-battery-pcba-b13860s',
    name: 'B13860S V4 Smart Battery PCBA',
    tagline: 'Smart battery control board',
    mainImage: '/images/products/smart-battery/05-002-00759.jpg',
    price: 74100,
    priceEUR: 17200,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Smart Battery',
    type: 'ACCESSORY',
  },

  // ==================== BATTERY CHARGERS ====================
  {
    sku: 'PC-PCK-10000',
    slug: 'parallel-charging-kit-combo',
    name: 'XAG Parallel Charging Kit Combo',
    tagline: '6KW parallel charging kit with mounting bracket',
    mainImage: '/images/products/battery-chargers/pc-pck-10000-1.jpg',
    price: 88400,
    priceEUR: 20600,
    compareAtPrice: 96200,
    compareAtPriceEUR: 22400,
    stock: 0,
    category: 'Battery Chargers',
    type: 'ACCESSORY',
  },
  {
    sku: '09-017-00069',
    slug: 'battery-s-charger-cm13600s',
    name: 'XAG Battery S-Charger CM13600S',
    tagline: 'Forced air-cooling charger for B13960S/B13970S/B141050',
    mainImage: '/images/products/battery-chargers/09-017-00069-1.jpg',
    price: 494000,
    priceEUR: 114900,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Battery Chargers',
    type: 'ACCESSORY',
  },
  {
    sku: '09-017-00059',
    slug: 'e-charger-cm15300d',
    name: 'XAG Battery E-Charger CM15300D',
    tagline: 'High-power battery charging solution',
    mainImage: '/images/products/battery-chargers/09-017-00059-1.jpg',
    price: 600600,
    priceEUR: 139700,
    compareAtPrice: 772200,
    compareAtPriceEUR: 179600,
    stock: 0,
    category: 'Battery Chargers',
    type: 'ACCESSORY',
  },
  {
    sku: '09-017-00065',
    slug: 'mist-cooling-charging-station',
    name: 'XAG Mist-Cooling Charging Station',
    tagline: 'Cooling and charging station for XAG batteries',
    mainImage: '/images/products/battery-chargers/09-017-00065-1.jpg',
    price: 92300,
    priceEUR: 21500,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Battery Chargers',
    type: 'ACCESSORY',
  },
  {
    sku: '09-017-00028',
    slug: 'water-cool-charging-tank',
    name: 'XAG 2022 Mod Water-Cool Charging Tank',
    tagline: 'Water-cooling charging tank for efficient battery charging',
    mainImage: '/images/products/battery-chargers/09-017-00028-3.png',
    price: 85800,
    priceEUR: 19900,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Battery Chargers',
    type: 'ACCESSORY',
  },
  {
    sku: '09-020-00016',
    slug: 'generator-supercharger-gc4000-plus',
    name: 'XAG Generator SuperCharger GC4000+',
    tagline: 'All-in-one generator and charger for XAG drones and UGVs',
    mainImage: '/images/products/battery-chargers/09-020-00016-1.jpg',
    price: 455000,
    priceEUR: 105000,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 5,
    category: 'Battery Chargers',
    type: 'ACCESSORY',
  },

  // ==================== TASK SYSTEM ====================
  {
    sku: '09-023-00025',
    slug: 'revospray-p3',
    name: 'XAG P100 Pro RevoSpray P3',
    tagline: '50L spray system with centrifugal atomizing nozzles',
    mainImage: '/images/products/task-system/09-023-00025-1.jpg',
    price: 910000,
    priceEUR: 211600,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Task System',
    type: 'ACCESSORY',
  },
  {
    sku: '09-023-00055',
    slug: 'revospray-p4',
    name: 'XAG P150 RevoSpray P4',
    tagline: 'Advanced spray system for P150 platform',
    mainImage: '/images/products/task-system/09-023-00055.jpg',
    price: 910000,
    priceEUR: 211600,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Task System',
    type: 'ACCESSORY',
  },
  {
    sku: '09-023-00054',
    slug: 'revocast-p4',
    name: 'XAG P150 RevoCast P4',
    tagline: 'Spreading system for P150 platform',
    mainImage: '/images/products/task-system/09-023-00054.jpg',
    price: 1040000,
    priceEUR: 241900,
    compareAtPrice: 1170000,
    compareAtPriceEUR: 272100,
    stock: 0,
    category: 'Task System',
    type: 'ACCESSORY',
  },
  {
    sku: '05-002-02262',
    slug: 'p100-pro-60l-upgrade-kit',
    name: 'XAG P100 Pro Upgrade Kit - 60L Container',
    tagline: '60L Smart Tank with Sub-Cover Refill Design',
    mainImage: '/images/products/task-system/05-002-02262.jpg',
    price: 743600,
    priceEUR: 172900,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Task System',
    type: 'ACCESSORY',
  },
  {
    sku: '09-023-00023',
    slug: 'revocast-p3',
    name: 'XAG P100 Pro RevoCast P3',
    tagline: '80L spreader system for dry solids 1-6mm',
    mainImage: '/images/products/task-system/09-023-00023-1.png',
    price: 1170000,
    priceEUR: 272100,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Task System',
    type: 'ACCESSORY',
  },

  // ==================== REMOTE CONTROLLER ====================
  {
    sku: '09-016-00085',
    slug: 'remote-controller-src5',
    name: 'XAG Remote Controller SRC5',
    tagline: '7.02" display, 20000mAh, 2km range',
    mainImage: '/images/products/remote-controller/09-016-00085-2.png',
    price: 598000,
    priceEUR: 139100,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Remote Controller',
    type: 'ACCESSORY',
  },
  {
    sku: '09-016-00053',
    slug: 'rc-arc3-pro',
    name: 'XAG RC ARC3 Pro',
    tagline: 'Compact controller with RTK positioning',
    mainImage: '/images/products/remote-controller/09-016-00053-2.png',
    price: 546000,
    priceEUR: 127000,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'Remote Controller',
    type: 'ACCESSORY',
  },

  // ==================== GNSS RTK ====================
  {
    sku: '09-016-00083',
    slug: 'gnss-xrtk7-mobile-station',
    name: 'XAG GNSS XRTK7 Mobile Station',
    tagline: 'Portable RTK with <5cm accuracy, 2km range',
    mainImage: '/images/products/gnss-rtk/09-016-00083-1.png',
    price: 475800,
    priceEUR: 110700,
    compareAtPrice: 603200,
    compareAtPriceEUR: 140300,
    stock: 0,
    category: 'GNSS RTK',
    type: 'ACCESSORY',
  },
  {
    sku: '09-010-00019',
    slug: 'gnss-rtk-fix-station',
    name: 'XAG GNSS RTK Fix Station',
    tagline: 'High-precision RTK module ±10mm accuracy',
    mainImage: '/images/products/gnss-rtk/09-010-00019-1.png',
    price: 1154400,
    priceEUR: 268500,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'GNSS RTK',
    type: 'ACCESSORY',
  },
  {
    sku: '09-010-00036',
    slug: 'gnss-xrtk4-rover',
    name: 'XAG GNSS XRTK4 Rover',
    tagline: 'RTK positioning module for agricultural use',
    mainImage: '/images/products/gnss-rtk/09-010-00036-1.jpg',
    price: 1144000,
    priceEUR: 266000,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'GNSS RTK',
    type: 'ACCESSORY',
  },
  {
    sku: '13-001-00056',
    slug: 'station-tripod',
    name: 'XAG Station Tripod',
    tagline: 'Tripod for GNSS RTK stations',
    mainImage: '/images/products/gnss-rtk/13-001-00056-1.png',
    price: 67600,
    priceEUR: 15700,
    compareAtPrice: null,
    compareAtPriceEUR: null,
    stock: 0,
    category: 'GNSS RTK',
    type: 'ACCESSORY',
  },
];

// POST - Seed products
export async function POST() {
  try {
    const prisma = await getPrisma();

    let created = 0;
    let skipped = 0;

    for (const product of seedProducts) {
      // Check if product already exists
      const existing = await prisma.product.findFirst({
        where: {
          OR: [{ sku: product.sku }, { slug: product.slug }],
        },
      });

      if (existing) {
        skipped++;
        continue;
      }

      await prisma.product.create({
        data: {
          sku: product.sku,
          slug: product.slug,
          name: product.name,
          tagline: product.tagline || null,
          mainImage: product.mainImage || null,
          price: product.price,
          priceEUR: product.priceEUR,
          compareAtPrice: product.compareAtPrice || null,
          compareAtPriceEUR: product.compareAtPriceEUR || null,
          stock: product.stock,
          lowStockThreshold: 5,
          category: product.category,
          type: product.type,
          isActive: true,
        },
      });
      created++;
    }

    return NextResponse.json({
      success: true,
      message: `Seeded ${created} products, skipped ${skipped} existing`,
      created,
      skipped,
      total: seedProducts.length,
    });
  } catch (error) {
    console.error('Failed to seed products:', error);
    return NextResponse.json(
      { error: 'Failed to seed products', details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}
